version: "2"
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=batch123
      - MYSQL_DATABASE=batchdb
      - MYSQL_USER=batchdb-user
      - MYSQL_PASSWORD=batch123
    ports:
        - 3307:3306
  web:
    image: spring-batch
    depends_on:
      - db
    ports:
          - 8070:8080
    environment:
          - DATABASE_HOST=db
          - DATABASE_USER=batchdb-user
          - DATABASE_PASSWORD=batch123
          - DATABASE_NAME=batchdb
          - DATABASE_PORT=3307


